### ISSUE TITLE
Python reputation system - get_ranks is not working

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#100]
See the following code throws error when PythonReputationService is used:
https://github.com/singnet/reputation/blob/master/agency/python/src/test_reputation.py

		# TODO fix PythonReputationService so it can pass the following
		"""
		r, ratings = rs.get_ratings({'ids':['1'],'since':dt1,'until':dt1})
		ratings = sorted(ratings, key=lambda elem: "%s %s" % (elem['from'], elem['to']))
		#print(ratings)
		self.assertEqual(len(ratings), 3)
		self.assertEqual(ratings[0]['value'], 100)
		self.assertEqual(ratings[1]['value'], 100)
		self.assertEqual(ratings[2]['value'],  50)
		r, ratings = rs.get_ratings({'ids':['1'],'since':dt2,'until':dt2})
		#print(ratings)
		self.assertEqual(len(ratings), 1)
		r, ratings = rs.get_ratings({'ids':['1'],'since':dt3,'until':dt3})
		#print(ratings)
		self.assertEqual(len(ratings), 1)
		"""

**Comment by nejc9921** [comment]
Issue #100 can now probably be closed. I uncommented it and made it work. There is another TODO below that issue:
"TODO fix either PythonReputationService or AigentsAPIReputationService 
		# so the raanks are rounded up consistently in the following block"
However, this is the problem with rounding and I think we said that assertequal could be wrong for 1% (as it is now). So, this TODO can probably be deleted as well. I just left it to see the issue, but might delete it in next iterations.
