### ISSUE TITLE
Study 5 real marketplaces

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#113]
Explore 5 real marketplaces using open publications, may order paid reports, find what is possible for the following :

- Market Ratios: 
-- buyers vs sellers - buyer ratio (BR)
-- honest buyers and sellers vs fake buyers and scamming sellers - fairness ratio (FR)
-- honest buyers vs honest sellers
-- fake buyers (including bots) vs scamming sellers
-- if there is a overlap between the categories above, estimate the overlap formally 
- Distributions of numbers of daily/weekly/monthly transactions for honest buyers vs scamming fake buyers - transaction ratio (TR) 
- Distributions of amounts per transactions for honest buyers vs scamming fake buyers - amount ratio (AR) 
- Ratios for newcomers and leavers - population replacement rates or average life spans, separately for four categories
-- honest sellers
-- honest buyers
-- scamming sellers
-- fake buyers (including bots)
- Time on the market (life spans) - average and range, separately for four categories
-- honest sellers
-- honest buyers
-- scamming sellers
-- fake buyers (including bots)
- Price ranges - like the prices of the most expensive and most cheap product on the market, number of price categories and distribution of the number of per-product-category sales  
- Possible abuse scenarios (if found along the way, will have separate study #131 otherwise)
- If possible, estimate presence and scale of "faked downratings" phenomenon, when competitors spending money to sink other competitors

**Comment by pennachin** [comment]
Regarding "population replacement rates or average life spans": ideally we'd have a rate for newcomers, but agents would leave the market based on some function of their profits and losses, rather than some average life span.

**Comment by nejc9921** [comment]
Findings so far:

https://docs.google.com/document/d/191gX-9Qa5tMoLHWQZyj3RLsf3IOsvw5PwnFHwsmmsyE/edit

**Comment by nejc9921** [comment]
Quick summary of findings:
https://docs.google.com/document/d/1bKr1JMwSL9eQJkbPEQBcF8vGrUqWcr8sJE0ZMxeC3vM/edit#heading=h.gjdgxs

**Comment by akolonin** [comment]
Conclusion:
https://docs.google.com/document/d/1MkaY3mysOj4XARWdNcaZZTrJux6KTbjO_gtgod_dPa4/edit#
TODO:  update spec

**Comment by akolonin** [comment]
@nejc9921 please check "4.1. Complicating simulation" in https://docs.google.com/document/d/1cAFAdJmDHNpIX1lYiYPEMHmjwB_T3-sUpnJ2M15_68o/edit?ts=5c8f8c01#heading=h.5qrdd2aoub69 - if it captures your findings.

**Comment by nejc9921** [comment]
yeah, looks good
