### ISSUE TITLE
Better financial metric

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#123]
Deborah wrote: "I would further add finding a better metric of marginal profit for bad agents entering the market. Profit from scam is not that metric, because bad agents keep trading the same penny, so its not a cost, and it also averages to zero.  I we are to assume it represented a cost of transactions, then we would find the margin, including the cost of transactions and expected benefits.  Right now, they can gain, because we haven't discussed entries to the market - we need to talk about entries to the market to get at the margin."
Cassio wrote: "In reality transaction costs are never zero. So the assumption that bad agents trade without cost is false. Our revised metric should reflect that. It should also compare profitability/effort of being bad vs being good, perhaps."

**Comment by deborahduong** [comment]
I think you should close this one, because you made a better financial metric to replace PFS already, called SGP
