### ISSUE TITLE
Fix handling downratings in Aigents Java, Python and tests 

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#127]
Downratings work weird for "Anton's" simplistic simulation:
https://docs.google.com/spreadsheets/d/1HbAjXZzj6E1meXyxPLS8f62LbhLRIv3lCwpSLgACt8I/edit#gid=1956896263
But they don't work for "Deborah's" advanced simulations:
https://docs.google.com/spreadsheets/d/1lNrbDUT2L_lqpn_-jwIBrWSCiHp6SJoBSkYUSPNuJx0/edit#gid=2080603677

**Comment by akolonin** [comment]
@nejc9921 the issue on Aigents Java side id fixed with #209, along with tests.
The expected range of the ratings is [0.0,1.0]. 
The Aigents Java fix is here:
https://github.com/aigents/aigents-java/commit/d55b8923a4c35c65212b399fceaec5d11c63cdad#diff-88798f3af72660c0a92c3fc9c9aadcf6R531
Now, please fix Python code so there is NO attempt to identify the range dynamically on the fly because it does not make sense if different ranges of ratings are accidentally used during the normal operations.

**Comment by akolonin** [comment]
@nejc9921 - if the "Now, please fix Python code so there is NO attempt to identify the range dynamically on the fly because it does not make sense if different ranges of ratings are accidentally used during the normal operations." is done?

**Comment by nejc9921** [comment]
Now it is commited in #234
