### ISSUE TITLE
Reputation abuse scenarios

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#131]
In extension to #113, need to study possible reputation system abuse (cheating gaming scenarios) studied and having parameters for simulation specified, similarly to what is done in
https://docs.google.com/document/d/1izovbeKmUSm253zfx-y0Dxg6aczkzU_Nnim2-fYmEX4/edit
in section "Identification of Reputation Gaming Attacks" but based on real marketplaces

**Comment by nejc9921** [comment]
Are you sure this is the right doc? There is no section "Identification of Reputation Gaming Attacks"...

**Comment by akolonin** [comment]
Fixed to https://docs.google.com/document/d/1izovbeKmUSm253zfx-y0Dxg6aczkzU_Nnim2-fYmEX4/edit

**Comment by nejc9921** [comment]
This one can be in a way merged with issue #113 . I am keeping the progress in: https://docs.google.com/document/d/191gX-9Qa5tMoLHWQZyj3RLsf3IOsvw5PwnFHwsmmsyE/edit
