### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by tiero** [singnet/reputation#155]
I propose to change the structure of the folders and files, to streamline import from other packages.

```
--- /reputation
--- --- here all python code 
--- /resources
--- --- /linuxbuild
--- --- /vendor
--- /scripts
```

 I would move the bin folder to resources, maybe under a vendor folder or even nicer we move the `bin` out from git tracking and store it to Github releases. When we launch the install scripts it will be downloaded.

Everything it is in `python/src`  would be uplifted up of two leveles in a `reputation` folder.

Rationale https://packaging.python.org/tutorials/packaging-projects/

All the things related to simulation will be dropped.

**Comment by tiero** [comment]
https://github.com/singnet/reputation/commit/a5a70edc3810f9d72b28e66a07367e1419fd34c3

**Comment by akolonin** [comment]
@tiero - what will be the process deploying jar files accordingly to sh and py scripts?

**Comment by akolonin** [comment]
I suggest in 3rd party and @deborahduong 's simulation code it should be imported as ether
import reputation.reputation_api
import reputation_agency.reputation_api
(not sure which of the two is better, small preference on "reputation.reputation_api")

**Comment by tiero** [comment]
Yes, for example, based on the soft refactor in #156, we use it like

`from <package-name> import *`

https://github.com/singnet/reputation-simulation/blob/master/snsim/reputation_simulation/ReputationSim.py#L20

In this case to just not breaks anything the package is called `agency`, but I like as well just `reputation`

**Comment by tiero** [comment]
We will open a dedicated one to refactor the binaries
