### ISSUE TITLE
Python RS does not account for 'decayed' and 'default' as expected

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#157]
The following code in PR https://github.com/singnet/reputation/pull/159
displays that Python RS does not handle 'decayed' as expected, there are two problems at least:
1) 'default':0 should effect in zero ratings
2) 'decayed':0.5 should be visible in properties 

This may be causing #135
The following code needs to uncomment some lines in "test_unranked" functions: 
``` 
	def test_unranked(self):
		print('Testing '+type(self).__name__+' unranked')
		rs = self.rs
		rs.set_parameters({'default':0.0,'decayed':0.5,'precision':1,'logratings':False})
		dt2 = datetime.date(2018, 1, 2)
		dt3 = datetime.date(2018, 1, 3)
		dt4 = datetime.date(2018, 1, 4)
		for unrated in [False]:
			print('Unrated:',unrated)
			rs.set_parameters({'unrated':unrated})
			print(rs.get_parameters())
			self.assertEqual( self.rs.clear_ratings(), 0 )
			self.assertEqual( self.rs.clear_ranks(), 0 )
			self.assertEqual( rs.put_ratings([{'from':1,'type':'rating','to':2,'value':1,'weight':1,'time':dt2}]), 0 )
			self.assertEqual(rs.update_ranks(dt2),0)
			ranks = rs.get_ranks_dict({'date':dt2})
			print(ranks)
			self.assertEqual( rs.put_ratings([{'from':1,'type':'rating','to':2,'value':1,'weight':1,'time':dt3}]), 0 )
			self.assertEqual( rs.put_ratings([{'from':3,'type':'rating','to':4,'value':1,'weight':1,'time':dt3}]), 0 )
			self.assertEqual(rs.update_ranks(dt3),0)
			ranks = rs.get_ranks_dict({'date':dt3})
			print(ranks)
			self.assertEqual( rs.put_ratings([{'from':1,'type':'rating','to':6,'value':1,'weight':1,'time':dt4}]), 0 )
			self.assertEqual( rs.put_ratings([{'from':3,'type':'rating','to':8,'value':1,'weight':1,'time':dt4}]), 0 )
			self.assertEqual( rs.put_ratings([{'from':5,'type':'rating','to':10,'value':1,'weight':1,'time':dt4}]), 0 )
			self.assertEqual(rs.update_ranks(dt4),0)
			ranks = rs.get_ranks_dict({'date':dt4})
			print(ranks)

...

anton-mac:src demo$ python test_aigents_reputation_api.py
Testing TestAigentsAPIReputationService unranked
Unrated: False
{'default': 0.0, 'decayed': 0.5, 'conservatism': 0.5, 'precision': 1, 'weighting': True, 'denomination': False, 'fullnorm': True, 'liquid': True, 'logranks': True, 'logratings': False, 'downrating': False, 'update_period': 1, 'aggregation': False, 'unrated': False}
{'2': 0.0}
{'2': 0.0, '4': 0.0}
{'2': 100.0, '4': 100.0, '10': 0.0, '6': 0.0, '8': 0.0}
.
----------------------------------------------------------------------
Ran 1 test in 0.429s

OK
anton-mac:src demo$ python test_reputation_service_api.py
Testing TestPythonReputationService unranked
Unrated: False
{'default': 0.0, 'conservatism': 0.5, 'precision': 1, 'weighting': True, 'fullnorm': True, 'liquid': True, 'logranks': True, 'aggregation': False, 'logratings': False, 'update_period': 1, 'use_ratings': True, 'date': datetime.date(2018, 1, 1), 'decayed': 0, 'downrating': False, 'denomination': False}
{'2': 100.0}
{'2': 100.0, '4': 50.0}
{'2': 100.0, '4': 50.0, '6': 100.0, '8': 100.0, '10': 100.0}
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
```

**Comment by nejc9921** [comment]
When looking at this, this seems to be the reason why it happens:

when updating ratings for each day, the function is receiving only 0 values. That's fine until we come to normalizations. Not all of the values can be 0 when we have normalizations. All values have to sum up to 1. The same problem would occur if all agents would have identical rating. What happens instead is that it then gives everybody a rating of 100. Here everybody is agent 2.

I can change this, but I remember I had the same issue when passing the unittests and I had to make this adjustment in order to pass them. I will then try to get them to default rating. I doubt this is what is producing error in Deborah's simulation since this seems to be the issue that can only be reproduce in very small samples - in unittests.

**Comment by akolonin** [comment]
@nejc9921 - for the def test_unranked(self): above, are you getting the same numbers now? If so, we can close this and consider #135 separately.

**Comment by nejc9921** [comment]
{'2': 0.0}
{'2': 0.0, '4': 0.0}
{'2': 0.0, '4': 0.0, '6': 0.0, '8': 0.0, '10': 0.0}

I think this is what we expect in the end.

**Comment by akolonin** [comment]
@nejc9921 - can you look what it written in the description above and run the code?
It clearly says:

anton-mac:src demo$ python test_aigents_reputation_api.py
Testing TestAigentsAPIReputationService unranked
Unrated: False
{'default': 0.0, 'decayed': 0.5, 'conservatism': 0.5, 'precision': 1, 'weighting': True, 'denomination': False, 'fullnorm': True, 'liquid': True, 'logranks': True, 'logratings': False, 'downrating': False, 'update_period': 1, 'aggregation': False, 'unrated': False}
{'2': 0.0}
{'2': 0.0, '4': 0.0}
{'2': 100.0, '4': 100.0, '10': 0.0, '6': 0.0, '8': 0.0}
.
----------------------------------------------------------------------
Ran 1 test in 0.429s

**Comment by akolonin** [comment]
Anton to double check zeroes.

**Comment by akolonin** [comment]
@nejc9921 see the explanation in the new test in https://github.com/singnet/reputation/pull/170 and code at https://github.com/aigents/aigents-java/blob/master/src/main/java/net/webstructor/peer/Reputationer.java#L390

**Comment by nejc9921** [comment]
@akolonin , explanation seems to have been deleted. Would it be possible to repeat it?

**Comment by akolonin** [comment]
@nejc9921 see https://github.com/singnet/reputation/pull/170/files and
https://github.com/singnet/reputation/blob/master/reputation/test_reputation.py#L552
