### ISSUE TITLE
Documentation for Reputation and Simulation

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#182]
We need:
1. PDF version of a spec (single document, self-contained) - @akolonin 
2. PEP-standard docstrings for API and major reputaion computational pipeline functions - with complex parameters and behaviour - @akolonin + @nejc9921 
5. github readme for reputation - @akolonin + @tiero  
4. PEP-standard docstrings for major simulation pipeline functions with complex parameters and behaviour - @deborahduong 
5. github readme for simulation and simulation assessment results - @deborahduong

**Comment by nejc9921** [comment]
Python code is commented and explained in-code. Other than that, the existing documents and papers (most of them published) are describing how calculations work in both Java and Python.
