### ISSUE TITLE
Downratings error in Python RS: cannot convert float NaN to integer 

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#185]
Got issue with the Python RS version code:
akolonin@Ubuntu-1604-xenial-64-minimal:~/aigents/reputation/reputation$ python reputation_scenario_test.py > test_params_python.txt
/home/akolonin/aigents/reputation/reputation/reputation_calculation.py:587: RuntimeWarning: invalid value encountered in double_scalars
 reputation[k] = (reputation[k]-min_value) /(max_value-min_value)
Traceback (most recent call last):
 File "reputation_scenario_test.py", line 247, in <module>
   reputation_simulate(good_agent,bad_agent, datetime.date(2018, 1, 1), days, True, rs, campaign = [sp,sip], verbose=False)
 File "/home/akolonin/aigents/reputation/reputation/reputation_scenario.py", line 203, in reputation_simulate
   ranks = rs.get_ranks_dict({'date':prev_date})
 File "/home/akolonin/aigents/reputation/reputation/reputation_service_api.py", line 307, in get_ranks_dict
   result[k] = my_round(result[k]*100,0)
 File "/home/akolonin/aigents/reputation/reputation/reputation_calculation.py", line 243, in my_round
   delta = part - int(part)
ValueError: cannot convert float NaN to integer

The script that I run: /home/akolonin/aigents/reputation/reputation/reputation_scenario_test_python_error.py

Seems like problem is with downratings:
rs.set_parameters({'fullnorm':True,'weighting':True ,'logratings':False,'downrating':True,'denomination':True ,'unrated':True,'default':0.0,'decayed':0.5,'ratings':1.0,'spendings':0.0,'conservatism':0.5})
print(rs.get_parameters(), end=" ")
reputation_simulate(good_agent,bad_agent, datetime.date(2018, 1, 1), days, True, rs, campaign = [sp,sip], verbose=False)

**Comment by akolonin** [comment]
The script which reproduce the same problem faster:
/home/akolonin/aigents/reputation/reputation/reputation_scenario_test_python_error2.py

**Comment by akolonin** [comment]
Anton Kolonin [11:49 PM]
akolonin@Ubuntu-1604-xenial-64-minimal:~/aigents/reputation/reputation$ git pull
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 15 (delta 3), reused 7 (delta 3), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/aigents/reputation
  fde3b20..4600110  master     -> origin/master
Updating fde3b20..4600110
Fast-forward
reputation/reputation_calculation.py | 6 ++++--
1 file changed, 4 insertions(+), 2 deletions(-)
akolonin@Ubuntu-1604-xenial-64-minimal:~/aigents/reputation/reputation$ python reputation_scenario_test_python_error.py
Traceback (most recent call last):
 File "reputation_scenario_test_python_error.py", line 28, in <module>
   from reputation_service_api import *
 File "/home/akolonin/aigents/reputation/reputation/reputation_service_api.py", line 27, in <module>
   from reputation_calculation import *
 File "/home/akolonin/aigents/reputation/reputation/reputation_calculation.py", line 472
   liquid = False,logratings=False,logranks=True) :
   ^
IndentationError: unexpected indent

**Comment by nejc9921** [comment]
should be fixed now.
