### ISSUE TITLE
Ranks from one run effect the next even though clear ranks and clear ratings called

### ISSUE THREAD

**Issue by deborahduong** [singnet/reputation#196]
I found a bug in the current java RS, that could possibly explain our discrepancies:  when called in batch, and there are several runs in a row, the ranks from one run bleed into the next run.   I checked this by running a scenario in isolation, and then running the same scenario as the third run of a batch.  You can see it clearer in the runs where the sip is half of the sp.   I double checked that I called clear ranks and clear ratings at the start of the new run with a breakpoint in

**Comment by nejc9921** [comment]
I believe this is something very similar to what I have found.
Looking at [the following transactions](https://docs.google.com/spreadsheets/d/1dS5OO_Y96bdtAiBp_QxM1oih1BgySX5BdgnhEy9-tT4/edit?usp=sharing), we get:
parameters:
{'default': 0.0, 'decayed': 0.5, 'conservatism': 0.5, 'precision': 0.01, 'weighting': True, 'denomination': True, 
'fullnorm': True, 'liquid': True, 'logranks': True, 'logratings': True
, 'downrating': False, 'update_period': 1, 'aggregation': False, 'unrated': True, 'ratings': 1.0, 'spendings': 0.0}

- For Python RS (the development of ranks):
date: 2018-01-01 00:00:00
ranks: {'2': 100.0, '3': 33.0, '4': 33.0, '9': 33.0}
date: 2018-01-02 00:00:00
ranks: {'2': 100.0, '3': 22.0, '4': 67.0, '9': 89.0}
date: 2018-01-03 00:00:00
ranks: {'2': 71.0, '3': 38.0, '4': 35.0, '9': 100.0}
date: 2018-01-04 00:00:00
ranks: {'2': 100.0, '3': 52.0, '4': 50.0, '9': 59.0}
date: 2018-01-05 00:00:00
ranks: {'2': 100.0, '3': 51.0, '4': 50.0, '9': 54.0, '11': 25.0}
date: 2018-01-06 00:00:00
ranks: {'2': 100.0, '3': 34.0, '4': 100.0, '9': 70.0, '11': 17.0}
date: 2018-01-07 00:00:00
ranks: {'2': 100.0, '3': 67.0, '4': 75.0, '9': 60.0, '11': 8.0}
date: 2018-01-08 00:00:00
ranks: {'2': 100.0, '3': 83.0, '4': 88.0, '9': 55.0, '11': 54.0}
date: 2018-01-09 00:00:00
ranks: {'2': 100.0, '3': 67.0, '4': 44.0, '9': 52.0, '11': 52.0, '13': 75.0}
date: 2018-01-10 00:00:00
ranks: {'2': 100.0, '3': 44.0, '4': 96.0, '9': 68.0, '11': 68.0, '13': 72.0}



- For Java RS we get:
date: 2018-01-01 00:00:00
ranks: {'2': 100.0, '3': 33.0, '4': 33.0, '9': 33.0}
date: 2018-01-02 00:00:00
ranks: {'1': 100.0, '2': 100.0}
date: 2018-01-03 00:00:00
ranks: {'2': 100.0, '1': 75.0, '9': 75.0}
date: 2018-01-04 00:00:00
ranks: {'2': 100.0, '3': 100.0, '1': 83.0, '4': 70.0, '9': 50.0}
date: 2018-01-05 00:00:00
ranks: {'4': 100.0, '3': 88.0, '1': 78.0, '2': 59.0, '9': 59.0, '11': 45.0}
date: 2018-01-06 00:00:00
ranks: {'3': 100.0, '1': 68.0, '2': 58.0, '9': 58.0, '11': 56.0, '4': 53.0}
date: 2018-01-07 00:00:00
ranks: {'11': 100.0, '4': 98.0, '3': 96.0, '1': 76.0, '9': 69.0, '2': 37.0}
date: 2018-01-08 00:00:00
ranks: {'4': 100.0, '3': 74.0, '1': 64.0, '9': 60.0, '11': 51.0, '2': 44.0}
date: 2018-01-09 00:00:00
ranks: {'4': 100.0, '3': 87.0, '13': 75.0, '1': 57.0, '9': 55.0, '11': 51.0, '2': 22.0}
date: 2018-01-10 00:00:00
ranks: {'3': 100.0, '1': 57.0, '9': 56.0, '11': 54.0, '4': 53.0, '13': 40.0, '2': 39.0}


Particularly problematic is the following:
date: 2018-01-01 00:00:00
ranks: {'2': 100.0, '3': 33.0, '4': 33.0, '9': 33.0}
date: 2018-01-02 00:00:00
ranks: {'1': 100.0, '2': 100.0}

If we take a look at the file I lineked, we have 5 transactions at date: 2018-01-02 00:00:00, going to agents 4, 9 and 3. Reproducible code can be found in "/home/nejc/other/github_pull3/reputation/reputation" in file "test_fixed.py".
@deborahduong : is this the same kind of error as you found? If so, can you post the list of parameters? I am looking into an issue at the moment.

**Comment by akolonin** [comment]
@deborahduong which script can I run to reproduce this?

**Comment by akolonin** [comment]
@deborahduong can you:
1) make sure that you call clear_ranks and clear_ratings
2) make it possible to do git pull and run the script reproducing the issue
?

**Comment by akolonin** [comment]
I have edited your file:
def print_ranks(self):
       since = datetime.date(2018, 1, 1)
       for day in range(184):
           prev_date = since + datetime.timedelta(days=(day-1))
           ranks = self.reputation_system.get_ranks_dict({'date':prev_date})
           print(prev_date,end=": ")
           print(ranks)

   def reset_reputation_system(self):
       if self.reputation_system:
           print("------------ before_clear ---------------")
           self.print_ranks()
           self.reputation_system.clear_ratings()
           self.reputation_system.clear_ranks()
           print("------------ after_clear ---------------")
           self.print_ranks()
           self.reputation_system.set_parameters({'fullnorm': True})

Here is what I have got:
akolonin@Ubuntu-1604-xenial-64-minimal:~/singnet/reputation-simulation$ grep -rne after_clear log_for_deborah.txt
187:------------ after_clear ---------------
740:------------ after_clear ---------------
1292:------------ after_clear ---------------
1844:------------ after_clear ---------------
2396:------------ after_clear ---------------
akolonin@Ubuntu-1604-xenial-64-minimal:~/singnet/reputation-simulation$ head -n 1302 log_for_deborah.txt | tail -n 11
------------ after_clear ---------------
2017-12-31: {}
2018-01-01: {}
2018-01-02: {}
2018-01-03: {}
2018-01-04: {}
2018-01-05: {}
2018-01-06: {}
2018-01-07: {}
2018-01-08: {}
2018-01-09: {}
akolonin@Ubuntu-1604-xenial-64-minimal:~/singnet/reputation-simulation$ head -n 1854 log_for_deborah.txt | tail -n 11
------------ after_clear ---------------
2017-12-31: {}
2018-01-01: {}
2018-01-02: {}
2018-01-03: {}
2018-01-04: {}
2018-01-05: {}
2018-01-06: {}
2018-01-07: {}
2018-01-08: {}
2018-01-09: {}
akolonin@Ubuntu-1604-xenial-64-minimal:~/singnet/reputation-simulation$ head -n 2406 log_for_deborah.txt | tail -n 11
------------ after_clear ---------------
2017-12-31: {}
2018-01-01: {}
2018-01-02: {}
2018-01-03: {}
2018-01-04: {}
2018-01-05: {}
2018-01-06: {}
2018-01-07: {}
2018-01-08: {}
2018-01-09: {}
$ pwd
/home/akolonin/singnet/reputation-simulation
It is completed, you can check it out:

"/home/akolonin/singnet/reputation-simulation/log_for_deborah.txt"

So far, I don't see any agents stuck in get_ratings...
