### ISSUE TITLE
make PythonReputationService callable in the module the same way AigentsAPIReputationService is

### ISSUE THREAD

**Issue by deborahduong** [singnet/reputation#231]
I can not use the PythonReputationService as a module, I would like to be able to call  , in reputation-simulation ReputationSim :  from reputation import PythonReputationService, but it is not there, and if I call   from reputation.reputation_service_api import PythonReputationService
I get error  File "/home/dduong/reputation/reputation/reputation_service_api.py", line 26, in <module>
    from reputation_service_api import *
ModuleNotFoundError: No module named 'reputation_service_api'
Seems like the same problem as before.

**Comment by akolonin** [comment]
@deborahduong - I think the fix is simple - do it as it is done in https://github.com/singnet/reputation/blob/master/reputation/aigents_reputation_api.py#L30
and make sure it is working.
@nejc9921 - please help if needed.

**Comment by deborahduong** [comment]
nope didn't work

**Comment by akolonin** [comment]
@tiero - can you look into that? Should be no issue with 100% pure Python code.
