### ISSUE TITLE
Python RS: Denominate ratings by “rating bias”

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#238]
According to section 3.2 of https://docs.google.com/document/d/1-O7avb_zJKvCXRvD0FmvyoVZdSmkDMlXRB5wsavpSAM/edit#

**Comment by akolonin** [comment]
Two issues:
1) Using simulation in https://github.com/singnet/reputation/pull/242, the rating_bias code is crashing:

$ python reputation_buying_test.py 
Without any RS
Organic: 24000 Sponsored: 4000 Organic2Sponsored: 8000 Organic/Sponsored: 6.0 LTS: 0.33 PFS: 2.0
With default RS PLRo=0
Organic: 6530 Sponsored: 4000 Organic2Sponsored: 6240 Organic/Sponsored: 1.63 LTS: 0.96 PFS: 1.56
With default RS PLRo=50
Organic: 8580 Sponsored: 4000 Organic2Sponsored: 6850 Organic/Sponsored: 2.15 LTS: 0.8 PFS: 1.71
With default RS PLRo=100
Organic: 8600 Sponsored: 4000 Organic2Sponsored: 6370 Organic/Sponsored: 2.15 LTS: 0.74 PFS: 1.59
With default RS PLRo=50, rating_bias
Traceback (most recent call last):
  File "reputation_buying_test.py", line 93, in <module>
    reputation_simulate(good_agent,bad_agent, datetime.date(2018, 1, 1), days, True, 80, 50, rs, verbose)
  File "/Users/demo/Documents/aigents/reputation/reputation/reputation_buying.py", line 239, in reputation_simulate
    rs.update_ranks(prev_date)
  File "/Users/demo/Documents/aigents/reputation/reputation/reputation_service_api.py", line 274, in update_ranks
    array1 , dates_array, to_array, rater_biases1 = reputation_calc_p1(self.current_ratings,self.conservatism,self.precision,self.temporal_aggregation,False,self.logratings,self.downrating,self.weighting,self.rater_biases[since])
  File "/Users/demo/Documents/aigents/reputation/reputation/reputation_calculation.py", line 150, in reputation_calc_p1
    rater_bias = update_biases(rater_bias,new_subset,conservatism)
  File "/Users/demo/Documents/aigents/reputation/reputation/reputation_calculation.py", line 360, in update_biases
    new_bias[k] = averages[k] * (1-conservatism) + conservatism * previous_bias[k]
KeyError: '41'

2) Need to implement weighing by pessimism:
When the reputation rank is computed for the period by WLR algorithm, the rating value is multiplied by "pessimism"=1-"average rating" at the same point where it is multiplied by “rater rank” and it is being normalized as usual after that. 
So those who always give 1-star ratings (0.0 on our scale) would have "pessimism"=1.0 and so maximum impact in case of occasional higher ratings while those who always provide 5-stars (1.0 on our scale) would counted at all. This approach would eliminate exponential effects and divisions by zero if using 1/”avarage_rating” as a weighting factor.

**Comment by nejc9921** [comment]
For problem 1, I fixed it (https://github.com/singnet/reputation/pull/243), the second one comes once I finish looking at those scammy reviews...

**Comment by akolonin** [comment]
Problem 1) if fixed but there is problem 3) to investigate further, unless it is fixed with 2):

3) Use of the setting does not make metrics better while it expectedly should, need to understand whether issue is on simulation side or reputation side:

$ python reputation_buying_test.py 
Without any RS
Organic: 24000 Sponsored: 4000 Organic2Sponsored: 8000 Organic/Sponsored: 6.0 LTS: 0.33 PFS: 2.0
With default RS PLRo=0
Organic: 6530 Sponsored: 4000 Organic2Sponsored: 6240 Organic/Sponsored: 1.63 LTS: 0.96 PFS: 1.56
With default RS PLRo=50
Organic: 8580 Sponsored: 4000 Organic2Sponsored: 6850 Organic/Sponsored: 2.15 LTS: 0.8 PFS: 1.71
With default RS PLRo=100
Organic: 8600 Sponsored: 4000 Organic2Sponsored: 6370 Organic/Sponsored: 2.15 LTS: 0.74 PFS: 1.59
With default RS PLRo=50, rating_bias
Organic: 8820 Sponsored: 4000 Organic2Sponsored: 7030 Organic/Sponsored: 2.21 LTS: 0.8 PFS: 1.76

**Comment by nejc9921** [comment]
#251 - number 2 should now be updated.
