### ISSUE TITLE
Python reputation system performance

### ISSUE THREAD

**Issue by akolonin** [singnet/reputation#83]
Need to make sure that Python reputation system work as fast as Java Aigents reputation system or faster and provides comparable results. So far, it works like that:
akolonin@Ubuntu-1604-xenial-64-minimal:~/aigents/reputation/agency/python/src$ python performance_test.py
Good: 804896115 Bad: 20128919 Good to Bad 2398032 Good/Bad: 39.98705121720645 Bad/Good_to_Bad: 8.393932608071953
Time spent Aigents: 11045.128473758698
Ratings is set to True, but no ratings were given. Changing the setting to False
Good: 804793094 Bad: 20127955 Good to Bad 76846730 Good/Bad: 39.983848036226235 Bad/Good_to_Bad: 0.26192337657048
Time spent Python: 1905.0442533493042

So, on the server 95.216.33.138 it works approximately 10 times faster but the Bad/Good_to_Bad: 0.26192337657048 compared to Java Aigents Bad/Good_to_Bad: 8.393932608071953 is too way off.

Similar results are reproduced on my laptop - good speed performance but quite different numbers:
anton-mac:src demo$ python performance_test.py
Good: 804896115 Bad: 20128919 Good to Bad 2398032 Good/Bad: 39.98705121720645 Bad/Good_to_Bad: 8.393932608071953
Time spent Aigents: 19587.70550107956
Ratings is set to True, but no ratings were given. Changing the setting to False
Good: 804793094 Bad: 20127955 Good to Bad 76846730 Good/Bad: 39.983848036226235 Bad/Good_to_Bad: 0.26192337657048
Time spent Python: 3752.7237200737

Need @nejc9921 to explore the reason, possible repeating the run with 10 agents X 10 days setup and exploring the histories.

So far, it seems like some of the parameters are interpreted differently.

**Comment by akolonin** [comment]
Nejc, I think you can double check this now if it works, give all unit tests pass now.

**Comment by akolonin** [comment]
Don't forget to fix along the way in reputation_service_api.py
class PythonReputationService(object):
should be:
class AigentsAPIReputationService(ReputationServiceBase):

**Comment by nejc9921** [comment]
Latter one should be fixed now (PythonReputationService to AigentsAPIReputationService), but also inspecting the original issue.

**Comment by nejc9921** [comment]
Ok in performance_test.py I have to change 1 line in order to have it run on Python simulation (should I push that change?). After that I get:
Good: 804909561 Bad: 20130794 Good to Bad 2434532 Good/Bad: 39.98399471973137 Bad/Good_to_Bad: 8.268855780084222
Time spent Aigents: 1910.4772143363953
Good: 804909561 Bad: 20130794 Good to Bad 2434532 Good/Bad: 39.98399471973137 Bad/Good_to_Bad: 8.268855780084222
Time spent Python: 1785.2959296703339

How do those results look like? What should I compare them with? I will run it few more times to see if I get any different results.

**Comment by akolonin** [comment]
I think again this is my fault with confusing mistyping/miscopypasting "PythonReputationService to AigentsAPIReputationService"
I mean INSTEAD 
class PythonReputationService(object):
IN SHOULD BE
class PythonReputationService(RatingService,RankingService):
class PythonReputationService(ReputationServiceBase):

We are comparing PythonReputationService against AigentsAPIReputationService, there is no point to compare the code against itself, right?

Otherwise, I don't see what is the line you changed saying "I have to change 1 line" so I can not reason why you are getting identical umbers and quite similar run time.

**Comment by nejc9921** [comment]
You are right! I commented the following line:
rs = AigentsAPIReputationService('http://localtest.com:1188/', 'john@doe.org', 'q', 'a', False, 'test', True)

And replaced it with Python reputation service. This indeed makes my tests so far useless.

But I did this for a reason. If I leave it, I get an error:
Specify proper url to Aigents server or run it locally, eg.
java -cp ../../bin/Aigents.jar:../../bin/* net.webstructor.agent.Farm store path './al_test.txt', cookie domain 
request http://localtest.com:1188/?my+name+john%40doe.org%2C+surname+john%40doe.org%2C+email+john%40doe.org. <class 'requests.exceptions.ConnectionError'>
Traceback (most recent call last):
  File "performance_test.py", line 58, in <module>
    rs = AigentsAPIReputationService('http://localtest.com:1188/', 'john@doe.org', 'q', 'a', False, 'test', True)
  File "C:\Users\User\Documents\work\SingularityNET\liquid rank\unittests\v4\python\src\aigents_reputation_api.py", line 46, in __init__
    self.create_session()
  File "C:\Users\User\Documents\work\SingularityNET\liquid rank\unittests\v4\python\src\aigents_reputation_api.py", line 64, in create_session
    assert output == 'What your secret question, secret answer?', 'Expecting secret question, secret answer'
AssertionError: Expecting secret question, secret answer
request http://localtest.com:1188/?Your+trusts+no+john%40doe.org. <class 'requests.exceptions.ConnectionError'>
Exception ignored in: <bound method AigentsAPIReputationService.__del__ of <aigents_reputation_api.AigentsAPIReputationService object at 0x000002870F6AEF60>>
Traceback (most recent call last):
  File "C:\Users\User\Documents\work\SingularityNET\liquid rank\unittests\v4\python\src\aigents_reputation_api.py", line 52, in __del__
    self.close_session()
  File "C:\Users\User\Documents\work\SingularityNET\liquid rank\unittests\v4\python\src\aigents_reputation_api.py", line 73, in close_session
    assert output.split()[0] == 'Ok.', 'Expecting Ok'
AssertionError: Expecting Ok

**Comment by akolonin** [comment]
Done, I think:
akolonin@Ubuntu-1604-xenial-64-minimal:~/aigents/reputation/agency/python/src$ python performance_test.py                   
Good: 804868354 Bad: 20128835 Good to Bad 2431040 Good/Bad: 39.98583892212341 Bad/Good_to_Bad: 8.279927520731867
Time spent Aigents: 10679.383123159409

Good: 804909561 Bad: 20130794 Good to Bad 2434532 Good/Bad: 39.98399471973137 Bad/Good_to_Bad: 8.268855780084222
Time spent Python: 973.437536239624
